# Generated by Django 5.2.14 on 2026-05-09 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(default=0.0)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receta', models.JSONField(default=dict, help_text="Ejemplo: {'INS-01': 15, 'INS-02': 200}")),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(default=0.0)),
                ('unidad_medida', models.CharField(choices=[('Gramos', 'Gramos'), ('Mililitros', 'Mililitros')], default='Gramos', max_length=20)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_preparada', models.IntegerField(default=1)),
                ('fecha_preparacion', models.DateTimeField(auto_now_add=True)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bebida')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.IntegerField(default=1)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bebida')),
            ],
        ),
    ]
