# Generated by Django 5.2.14 on 2026-05-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='id_producto',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='receta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id_producto',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
